[2024-03-23T19:45:56.968+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_bigquery.create_retail_dataset manual__2024-03-23T19:43:03.060824+00:00 [queued]>
[2024-03-23T19:45:56.982+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_bigquery.create_retail_dataset manual__2024-03-23T19:43:03.060824+00:00 [queued]>
[2024-03-23T19:45:56.983+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2024-03-23T19:45:57.001+0000] {taskinstance.py:2191} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_retail_dataset> on 2024-03-23 19:43:03.060824+00:00
[2024-03-23T19:45:57.009+0000] {standard_task_runner.py:60} INFO - Started process 9132 to run task
[2024-03-23T19:45:57.014+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_bigquery', 'create_retail_dataset', 'manual__2024-03-23T19:43:03.060824+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpz5k9zic1']
[2024-03-23T19:45:57.017+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask create_retail_dataset
[2024-03-23T19:45:57.071+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_to_bigquery.create_retail_dataset manual__2024-03-23T19:43:03.060824+00:00 [running]> on host 8a685a05c3f5
[2024-03-23T19:45:57.176+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='minhduc' AIRFLOW_CTX_DAG_ID='etl_to_bigquery' AIRFLOW_CTX_TASK_ID='create_retail_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T19:43:03.060824+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-23T19:43:03.060824+00:00'
[2024-03-23T19:45:57.189+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-23T19:45:57.191+0000] {base.py:83} INFO - Using connection ID 'gcp' for task execution.
[2024-03-23T19:45:57.193+0000] {bigquery.py:468} INFO - datasetId was not specified in `dataset_reference`. Will use default value retail.
[2024-03-23T19:45:57.193+0000] {bigquery.py:468} INFO - projectId was not specified in `dataset_reference`. Will use default value steady-monitor-415517.
[2024-03-23T19:45:57.194+0000] {bigquery.py:479} INFO - Creating dataset: retail in project: steady-monitor-415517 
[2024-03-23T19:45:58.775+0000] {bigquery.py:1932} INFO - Dataset retail already exists.
[2024-03-23T19:45:58.827+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_to_bigquery, task_id=create_retail_dataset, execution_date=20240323T194303, start_date=20240323T194556, end_date=20240323T194558
[2024-03-23T19:45:58.874+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-23T19:45:58.913+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
