[2024-03-25T15:57:04.653+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_bigquery.create_retail_dataset manual__2024-03-25T08:55:15.952824+00:00 [queued]>
[2024-03-25T15:57:04.665+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_bigquery.create_retail_dataset manual__2024-03-25T08:55:15.952824+00:00 [queued]>
[2024-03-25T15:57:04.665+0700] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2024-03-25T15:57:04.686+0700] {taskinstance.py:2191} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_retail_dataset> on 2024-03-25 08:55:15.952824+00:00
[2024-03-25T15:57:04.695+0700] {standard_task_runner.py:60} INFO - Started process 404 to run task
[2024-03-25T15:57:04.699+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_bigquery', 'create_retail_dataset', 'manual__2024-03-25T08:55:15.952824+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp19hykvgf']
[2024-03-25T15:57:04.702+0700] {standard_task_runner.py:88} INFO - Job 11: Subtask create_retail_dataset
[2024-03-25T15:57:04.759+0700] {task_command.py:423} INFO - Running <TaskInstance: etl_to_bigquery.create_retail_dataset manual__2024-03-25T08:55:15.952824+00:00 [running]> on host b24fc08bdd37
[2024-03-25T15:57:04.870+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='minhduc' AIRFLOW_CTX_DAG_ID='etl_to_bigquery' AIRFLOW_CTX_TASK_ID='create_retail_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T08:55:15.952824+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-25T08:55:15.952824+00:00'
[2024-03-25T15:57:04.882+0700] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-25T15:57:04.884+0700] {base.py:83} INFO - Using connection ID 'gcp' for task execution.
[2024-03-25T15:57:04.885+0700] {bigquery.py:468} INFO - datasetId was not specified in `dataset_reference`. Will use default value retail.
[2024-03-25T15:57:04.886+0700] {bigquery.py:468} INFO - projectId was not specified in `dataset_reference`. Will use default value steady-monitor-415517.
[2024-03-25T15:57:04.887+0700] {bigquery.py:479} INFO - Creating dataset: retail in project: steady-monitor-415517 
[2024-03-25T15:57:06.524+0700] {bigquery.py:1932} INFO - Dataset retail already exists.
[2024-03-25T15:57:06.585+0700] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_to_bigquery, task_id=create_retail_dataset, execution_date=20240325T085515, start_date=20240325T085704, end_date=20240325T085706
[2024-03-25T15:57:06.639+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-25T15:57:06.682+0700] {taskinstance.py:3280} INFO - 2 downstream tasks scheduled from follow-on schedule check
