[2024-03-25T21:46:35.570+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_bigquery.dbt_build_warehouse manual__2024-03-25T14:41:01.093869+00:00 [queued]>
[2024-03-25T21:46:35.585+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_bigquery.dbt_build_warehouse manual__2024-03-25T14:41:01.093869+00:00 [queued]>
[2024-03-25T21:46:35.586+0700] {taskinstance.py:2170} INFO - Starting attempt 4 of 5
[2024-03-25T21:46:35.604+0700] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_build_warehouse> on 2024-03-25 14:41:01.093869+00:00
[2024-03-25T21:46:35.613+0700] {standard_task_runner.py:60} INFO - Started process 6663 to run task
[2024-03-25T21:46:35.617+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_bigquery', 'dbt_build_warehouse', 'manual__2024-03-25T14:41:01.093869+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp3rmcneb6']
[2024-03-25T21:46:35.619+0700] {standard_task_runner.py:88} INFO - Job 42: Subtask dbt_build_warehouse
[2024-03-25T21:46:35.673+0700] {task_command.py:423} INFO - Running <TaskInstance: etl_to_bigquery.dbt_build_warehouse manual__2024-03-25T14:41:01.093869+00:00 [running]> on host b24fc08bdd37
[2024-03-25T21:46:35.774+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='minhduc' AIRFLOW_CTX_DAG_ID='etl_to_bigquery' AIRFLOW_CTX_TASK_ID='dbt_build_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T14:41:01.093869+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-25T14:41:01.093869+00:00'
[2024-03-25T21:46:35.777+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-25T21:46:35.779+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dags/dbt_transform && cat hello.txt']
[2024-03-25T21:46:35.801+0700] {subprocess.py:86} INFO - Output:
[2024-03-25T21:46:35.807+0700] {subprocess.py:93} INFO - cat: hello.txt: No such file or directory
[2024-03-25T21:46:35.808+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-25T21:46:35.823+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-25T21:46:35.829+0700] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_to_bigquery, task_id=dbt_build_warehouse, execution_date=20240325T144101, start_date=20240325T144635, end_date=20240325T144635
[2024-03-25T21:46:35.846+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 42 for task dbt_build_warehouse (Bash command failed. The command returned a non-zero exit code 1.; 6663)
[2024-03-25T21:46:35.869+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-25T21:46:35.900+0700] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
